# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name:
    url: /
    weight: 10
  - name: Recipe Blog
    url: /
    weight: 20
  - name: 
    url: /
    weight: 30